# Generated by Django 2.2.7 on 2019-12-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='num_places',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
