# Generated by Django 2.2.7 on 2019-12-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_flight_num_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='places',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
