# Generated by Django 2.2.8 on 2020-01-06 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_reservation_places'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='places',
        ),
    ]
