# Generated by Django 3.0.2 on 2020-01-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_remove_reservation_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='iata_code',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='airline',
            name='icao_code',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_date',
            field=models.DateTimeField(),
        ),
    ]
